name: gpt4all_dart_binding
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^2.18.1

dependencies:
  ffi: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
