name: gpt4all
description: Dart binding for the GPT4All C/C++ libraries and models.
version: 0.1.0
repository: https://github.com/finkmoritz/gpt4all
documentation: https://github.com/finkmoritz/gpt4all/blob/main/README.md

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
