name: gpt4all_dart_binding
description: Dart binding for the GPT4All C/C++ libraries and models.
version: 0.1.0

environment:
  sdk: ^2.18.1

dependencies:
  ffi: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
