version: "3.8"

services:
  gpt4all_api:
    image: gpt4all_api
    container_name: gpt4all_api
    restart: always
    ports:
      - "4891:4891"
    env_file:
      - .env
    environment:
      - APP_ENVIRONMENT=dev
      - WEB_CONCURRENCY=30
      - LOGLEVEL=debug
      - PORT=4891
      - model=${MODEL_BIN}
      - inference_mode=cpu
    volumes:
      - './gpt4all_api/app:/app'
      - './gpt4all_api/models:/models'
      - './embeddings-files:/app/embeddings-files' # Add this line
    command: ["/start-reload.sh"]
    deploy:
      resources:
        limits:
          cpus: '20'
          memory: 120G
        reservations:
          cpus: '12'
          memory: 12G
